import { Router, Request, Response } from 'express';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { excelService } from '../services/excel-service';
import { requireAuth } from '../middleware/auth';
import { db } from '../db';
import { 
  animals, 
  animalHealthRecords, 
  timesheets, 
  staffProfiles, 
  users,
  farmHazards,
  equipment,
  equipmentServiceHistory,
  tasks,
} from '@shared/schema';
import { eq, and, gte, lte, sql, desc, count, sum, inArray } from 'drizzle-orm';
import logger from '../config/logger';

const router = Router();

// Extend jsPDF type for autoTable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
    lastAutoTable: { finalY: number };
  }
}

// Generate PDF report
router.post('/api/reports/generate-pdf', async (req: Request, res: Response) => {
  try {
    const { reportType, dateRange, sections, farmName = 'Demo Farm' } = req.body;
    
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Header
    doc.setFontSize(20);
    doc.setTextColor(30, 57, 50); // Dark green
    doc.text(getReportTitle(reportType), pageWidth / 2, 20, { align: 'center' });
    
    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text(farmName, pageWidth / 2, 28, { align: 'center' });
    doc.text(`Generated: ${new Date().toLocaleDateString('en-NZ')}`, pageWidth / 2, 35, { align: 'center' });
    
    if (dateRange) {
      doc.text(`Period: ${dateRange.start} to ${dateRange.end}`, pageWidth / 2, 42, { align: 'center' });
    }
    
    // Add horizontal line
    doc.setDrawColor(30, 57, 50);
    doc.setLineWidth(0.5);
    doc.line(20, 48, pageWidth - 20, 48);
    
    let yPosition = 58;
    
    // Generate content based on report type
    switch (reportType) {
      case 'nzfap':
        yPosition = generateNZFAPReport(doc, yPosition, sections);
        break;
      case 'fwfp':
        yPosition = generateFWFPReport(doc, yPosition, sections);
        break;
      case 'fep':
        yPosition = generateFEPReport(doc, yPosition, sections);
        break;
      case 'nait':
        yPosition = generateNAITReport(doc, yPosition, sections);
        break;
      case 'herd-performance':
        yPosition = generateHerdPerformanceReport(doc, yPosition, sections);
        break;
      case 'financial-summary':
        yPosition = generateFinancialReport(doc, yPosition, sections);
        break;
      case 'treatment-records':
        yPosition = generateTreatmentReport(doc, yPosition, sections);
        break;
      default:
        yPosition = generateCustomReport(doc, yPosition, sections);
    }
    
    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(150);
      doc.text(
        `Page ${i} of ${pageCount}`,
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: 'center' }
      );
      doc.text(
        'Generated by Pulse Farm Management',
        20,
        doc.internal.pageSize.getHeight() - 10
      );
    }
    
    // Return PDF as base64
    const pdfBase64 = doc.output('datauristring');
    
    res.json({
      success: true,
      pdf: pdfBase64,
      filename: `${reportType}-report-${new Date().toISOString().slice(0, 10)}.pdf`,
    });
  } catch (error) {
    console.error('PDF generation error:', error);
    res.status(500).json({ error: 'Failed to generate PDF report' });
  }
});

// Download PDF directly
router.get('/api/reports/download/:reportType', async (req: Request, res: Response) => {
  try {
    const { reportType } = req.params;
    const { startDate, endDate } = req.query;
    
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Generate report based on type
    doc.setFontSize(20);
    doc.text(getReportTitle(reportType), pageWidth / 2, 20, { align: 'center' });
    
    let yPosition = 40;
    
    switch (reportType) {
      case 'nzfap':
        yPosition = generateNZFAPReport(doc, yPosition);
        break;
      case 'financial':
        yPosition = generateFinancialReport(doc, yPosition);
        break;
      default:
        doc.text('Report content will be generated here', 20, yPosition);
    }
    
    // Set response headers for PDF download
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=${reportType}-report.pdf`);
    
    // Send PDF buffer
    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
    res.send(pdfBuffer);
  } catch (error) {
    console.error('PDF download error:', error);
    res.status(500).json({ error: 'Failed to download PDF report' });
  }
});

// Generate Excel report
router.post('/api/reports/generate-excel', async (req: Request, res: Response) => {
  try {
    const { reportType, dateRange, farmName = 'Demo Farm' } = req.body;
    
    let workbook;
    
    switch (reportType) {
      case 'financial-summary':
        workbook = excelService.generateFinancialReport({
          summary: {
            totalRevenue: 1200000,
            totalCosts: 850000,
            netProfit: 350000,
            profitMargin: 29.2,
            revenueChange: 5.5,
            costChange: 3.2,
          },
          revenueBreakdown: [
            { category: 'Milk Revenue', amount: 1020000, percentage: 85 },
            { category: 'Livestock Sales', amount: 150000, percentage: 12.5 },
            { category: 'Other Income', amount: 30000, percentage: 2.5 },
          ],
          costBreakdown: [
            { category: 'Feed & Grazing', amount: 180000, percentage: 21.2 },
            { category: 'Labour', amount: 150000, percentage: 17.6 },
            { category: 'Animal Health', amount: 48000, percentage: 5.6 },
            { category: 'Fertilizer', amount: 96000, percentage: 11.3 },
            { category: 'Repairs', amount: 60000, percentage: 7.1 },
            { category: 'Other', amount: 316000, percentage: 37.2 },
          ],
          monthlyData: generateMonthlyData(),
          budgetComparison: [
            { category: 'Feed', budget: 180000, actual: 172000, variance: -8000, variancePercent: -4.4 },
            { category: 'Labour', budget: 150000, actual: 148000, variance: -2000, variancePercent: -1.3 },
            { category: 'Animal Health', budget: 50000, actual: 48000, variance: -2000, variancePercent: -4.0 },
          ],
        });
        break;
        
      case 'herd-performance':
        workbook = excelService.generateHerdPerformanceReport({
          production: [
            { metric: 'Total Milk Solids (kg)', current: 118500, previous: 112300, change: 5.5, target: 120000 },
            { metric: 'MS per Cow (kg)', current: 395, previous: 374, change: 5.6, target: 400 },
            { metric: 'MS per Hectare (kg)', current: 1185, previous: 1123, change: 5.5, target: 1200 },
            { metric: 'Peak Milk (L/cow/day)', current: 2.2, previous: 2.1, change: 4.8, target: 2.3 },
          ],
          reproduction: [
            { metric: '6-Week In-Calf Rate', result: '72%', target: '75%', status: 'Below Target' },
            { metric: 'Empty Rate', result: '9%', target: '10%', status: 'On Track' },
            { metric: 'Submission Rate', result: '88%', target: '85%', status: 'Exceeding' },
          ],
          health: [
            { metric: 'Bulk SCC (000/ml)', value: 145, industryAvg: 180, status: 'Good' },
            { metric: 'Lameness Rate', value: '5%', industryAvg: '8%', status: 'Good' },
            { metric: 'Mastitis Rate', value: '8%', industryAvg: '12%', status: 'Good' },
          ],
        });
        break;
        
      case 'nait':
        workbook = excelService.generateNAITReport({
          summary: {
            naitNumber: '12345678',
            totalAnimals: 312,
            movements: 45,
            complianceStatus: '100%',
          },
          movements: [
            { date: new Date(), type: 'Arrival', animalId: 'NZ001234567', location: 'Farm ABC', registered: 'Yes' },
            { date: new Date(), type: 'Departure', animalId: 'NZ001234568', location: 'Sale Yards', registered: 'Yes' },
            { date: new Date(), type: 'Death', animalId: 'NZ001234569', location: 'On Farm', registered: 'Yes' },
          ],
          animals: [
            { naitTag: 'NZ001234567', visualTag: 'A001', species: 'Cattle', birthDate: new Date('2022-08-15'), registrationDate: new Date('2022-08-20') },
            { naitTag: 'NZ001234568', visualTag: 'A002', species: 'Cattle', birthDate: new Date('2022-09-01'), registrationDate: new Date('2022-09-05') },
          ],
        });
        break;
        
      default:
        workbook = excelService.generateWorkbook({
          filename: 'Report',
          sheets: [{
            name: 'Data',
            columns: [
              { header: 'Report Type', key: 'type', width: 20 },
              { header: 'Generated', key: 'date', width: 20 },
            ],
            data: [{ type: reportType, date: new Date().toLocaleDateString('en-NZ') }],
          }],
        });
    }
    
    const excelBase64 = excelService.toBase64(workbook);
    
    res.json({
      success: true,
      excel: excelBase64,
      filename: `${reportType}-report-${new Date().toISOString().slice(0, 10)}.xlsx`,
    });
  } catch (error) {
    console.error('Excel generation error:', error);
    res.status(500).json({ error: 'Failed to generate Excel report' });
  }
});

// Download Excel directly
router.get('/api/reports/download-excel/:reportType', async (req: Request, res: Response) => {
  try {
    const { reportType } = req.params;
    
    // Generate a simple workbook for direct download
    const workbook = excelService.generateWorkbook({
      filename: `${reportType} Report`,
      sheets: [{
        name: 'Summary',
        title: `${getReportTitle(reportType)}`,
        subtitle: `Generated: ${new Date().toLocaleDateString('en-NZ')}`,
        columns: [
          { header: 'Metric', key: 'metric', width: 25 },
          { header: 'Value', key: 'value', width: 20 },
        ],
        data: [
          { metric: 'Report Type', value: reportType },
          { metric: 'Generated Date', value: new Date().toLocaleDateString('en-NZ') },
          { metric: 'Farm', value: 'Demo Farm' },
        ],
      }],
    });
    
    const buffer = excelService.toBuffer(workbook);
    
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', `attachment; filename=${reportType}-report.xlsx`);
    res.send(buffer);
  } catch (error) {
    console.error('Excel download error:', error);
    res.status(500).json({ error: 'Failed to download Excel report' });
  }
});

// Helper function to generate monthly data
function generateMonthlyData() {
  const months = [];
  const now = new Date();
  for (let i = 11; i >= 0; i--) {
    const date = new Date(now.getFullYear(), now.getMonth() - i, 1);
    const seasonalFactor = getSeasonalFactor(date.getMonth());
    const revenue = Math.round(100000 * seasonalFactor);
    const costs = Math.round(70000 * (0.9 + Math.random() * 0.2));
    months.push({
      month: date.toISOString().slice(0, 7),
      revenue,
      costs,
      profit: revenue - costs,
    });
  }
  return months;
}

function getSeasonalFactor(month: number): number {
  const factors = [0.6, 0.4, 0.2, 0.1, 0.05, 0.02, 0.02, 0.3, 0.7, 1.0, 1.2, 1.0];
  return factors[month];
}

// Schedule report
router.post('/api/reports/schedule', async (req: Request, res: Response) => {
  try {
    const { reportId, frequency, recipients, format, nextRun } = req.body;
    
    // In production, save to database and set up cron job
    // For now, return success
    const scheduleId = `schedule-${Date.now()}`;
    
    res.json({
      success: true,
      scheduleId,
      message: `Report scheduled to run ${frequency}`,
      nextRun: nextRun || calculateNextRun(frequency),
    });
  } catch (error) {
    console.error('Schedule report error:', error);
    res.status(500).json({ error: 'Failed to schedule report' });
  }
});

// Get scheduled reports
router.get('/api/reports/scheduled', async (req: Request, res: Response) => {
  try {
    // In production, fetch from database
    const scheduledReports = [
      {
        id: 's1',
        reportId: 'nait',
        reportName: 'NAIT Compliance Report',
        frequency: 'monthly',
        nextRun: getNextMonthDate(),
        recipients: ['farm@example.com'],
        format: 'PDF',
        status: 'active',
        lastSent: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 's2',
        reportId: 'herd-performance',
        reportName: 'Herd Performance Report',
        frequency: 'monthly',
        nextRun: getNextMonthDate(),
        recipients: ['farm@example.com', 'manager@example.com'],
        format: 'PDF',
        status: 'active',
        lastSent: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ];
    
    res.json(scheduledReports);
  } catch (error) {
    console.error('Get scheduled reports error:', error);
    res.status(500).json({ error: 'Failed to fetch scheduled reports' });
  }
});

// Delete scheduled report
router.delete('/api/reports/scheduled/:id', async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    // In production, delete from database
    res.json({ success: true, message: 'Scheduled report deleted' });
  } catch (error) {
    console.error('Delete scheduled report error:', error);
    res.status(500).json({ error: 'Failed to delete scheduled report' });
  }
});

// Get report history
router.get('/api/reports/history', async (req: Request, res: Response) => {
  try {
    const { limit = 20 } = req.query;
    
    // In production, fetch from database
    const history = [
      {
        id: 'g1',
        name: 'NZFAP Compliance Report 2024',
        type: 'Compliance',
        generatedAt: new Date().toISOString(),
        generatedBy: 'System',
        format: 'PDF',
        size: '2.4 MB',
        status: 'ready',
      },
      {
        id: 'g2',
        name: 'Herd Performance - December 2024',
        type: 'Production',
        generatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
        generatedBy: 'System',
        format: 'PDF',
        size: '1.8 MB',
        status: 'ready',
      },
    ];
    
    res.json(history);
  } catch (error) {
    console.error('Get report history error:', error);
    res.status(500).json({ error: 'Failed to fetch report history' });
  }
});

// Helper functions
function getReportTitle(reportType: string): string {
  const titles: Record<string, string> = {
    'nzfap': 'NZFAP Compliance Report',
    'fwfp': 'Freshwater Farm Plan Report',
    'fep': 'Farm Environment Plan',
    'nait': 'NAIT Compliance Report',
    'herd-performance': 'Herd Performance Report',
    'financial-summary': 'Financial Summary Report',
    'treatment-records': 'Treatment Records Report',
  };
  return titles[reportType] || 'Farm Report';
}

function generateNZFAPReport(doc: jsPDF, startY: number, sections?: string[]): number {
  let y = startY;
  
  // Executive Summary
  doc.setFontSize(14);
  doc.setTextColor(30, 57, 50);
  doc.text('Executive Summary', 20, y);
  y += 10;
  
  doc.setFontSize(10);
  doc.setTextColor(60);
  doc.text('Overall Compliance Score: 92%', 20, y);
  y += 6;
  doc.text('Audit Status: Certified', 20, y);
  y += 6;
  doc.text('Next Audit Due: March 2025', 20, y);
  y += 15;
  
  // Compliance Summary Table
  doc.autoTable({
    startY: y,
    head: [['Category', 'Status', 'Score', 'Items Checked']],
    body: [
      ['Animal Welfare', 'Compliant', '95%', '12/12'],
      ['Biosecurity', 'Compliant', '90%', '8/8'],
      ['Food Safety', 'Compliant', '88%', '10/10'],
      ['Environment', 'Minor Issues', '85%', '9/10'],
      ['People', 'Compliant', '92%', '6/6'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 57, 50] },
  });
  
  y = doc.lastAutoTable.finalY + 15;
  
  // Non-Compliance Items
  doc.setFontSize(14);
  doc.setTextColor(30, 57, 50);
  doc.text('Items Requiring Attention', 20, y);
  y += 10;
  
  doc.autoTable({
    startY: y,
    head: [['Item', 'Category', 'Priority', 'Due Date']],
    body: [
      ['Update effluent management plan', 'Environment', 'Medium', '2024-03-15'],
      ['Staff training refresher', 'People', 'Low', '2024-04-01'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [184, 150, 62] },
  });
  
  return doc.lastAutoTable.finalY + 10;
}

function generateFWFPReport(doc: jsPDF, startY: number, sections?: string[]): number {
  let y = startY;
  
  doc.setFontSize(14);
  doc.setTextColor(30, 57, 50);
  doc.text('Freshwater Farm Plan Summary', 20, y);
  y += 10;
  
  doc.setFontSize(10);
  doc.setTextColor(60);
  doc.text('Plan Status: Active', 20, y);
  y += 6;
  doc.text('Certification: Certified until December 2025', 20, y);
  y += 6;
  doc.text('Actions Completed: 18/24 (75%)', 20, y);
  y += 15;
  
  // Risk Assessment Summary
  doc.autoTable({
    startY: y,
    head: [['Risk Area', 'Risk Level', 'Mitigation Status', 'Review Date']],
    body: [
      ['Nitrogen Leaching', 'Medium', 'In Progress', '2024-06-01'],
      ['Sediment Runoff', 'Low', 'Complete', '2024-03-01'],
      ['E. coli Contamination', 'Medium', 'In Progress', '2024-05-15'],
      ['Phosphorus Loss', 'Low', 'Complete', '2024-02-01'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 57, 50] },
  });
  
  return doc.lastAutoTable.finalY + 10;
}

function generateFEPReport(doc: jsPDF, startY: number, sections?: string[]): number {
  let y = startY;
  
  doc.setFontSize(14);
  doc.setTextColor(30, 57, 50);
  doc.text('Environmental Compliance Summary', 20, y);
  y += 15;
  
  doc.autoTable({
    startY: y,
    head: [['Metric', 'Current', 'Target', 'Status']],
    body: [
      ['Nitrogen Leaching (kg N/ha)', '28', '35', 'On Track'],
      ['GHG Emissions (t CO2e/ha)', '9.2', '10.5', 'On Track'],
      ['Water Quality Index', '85%', '80%', 'Exceeding'],
      ['Riparian Planting (m)', '2,450', '3,000', 'In Progress'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 57, 50] },
  });
  
  return doc.lastAutoTable.finalY + 10;
}

function generateNAITReport(doc: jsPDF, startY: number, sections?: string[]): number {
  let y = startY;
  
  doc.setFontSize(14);
  doc.setTextColor(30, 57, 50);
  doc.text('NAIT Compliance Summary', 20, y);
  y += 10;
  
  doc.setFontSize(10);
  doc.setTextColor(60);
  doc.text('NAIT Number: 12345678', 20, y);
  y += 6;
  doc.text('Total Animals Registered: 312', 20, y);
  y += 6;
  doc.text('Movements This Period: 45', 20, y);
  y += 15;
  
  doc.autoTable({
    startY: y,
    head: [['Movement Type', 'Count', 'Registered', 'Compliance']],
    body: [
      ['Arrivals', '23', '23', '100%'],
      ['Departures', '18', '18', '100%'],
      ['Deaths', '4', '4', '100%'],
      ['Tag Replacements', '2', '2', '100%'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 57, 50] },
  });
  
  return doc.lastAutoTable.finalY + 10;
}

function generateHerdPerformanceReport(doc: jsPDF, startY: number, sections?: string[]): number {
  let y = startY;
  
  doc.setFontSize(14);
  doc.setTextColor(30, 57, 50);
  doc.text('Production Summary', 20, y);
  y += 15;
  
  doc.autoTable({
    startY: y,
    head: [['Metric', 'This Season', 'Last Season', 'Change']],
    body: [
      ['Total Milk Solids (kg)', '118,500', '112,300', '+5.5%'],
      ['MS per Cow (kg)', '395', '374', '+5.6%'],
      ['MS per Hectare (kg)', '1,185', '1,123', '+5.5%'],
      ['Peak Milk (L/cow/day)', '2.2', '2.1', '+4.8%'],
      ['Milking Days', '275', '270', '+1.9%'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 57, 50] },
  });
  
  y = doc.lastAutoTable.finalY + 15;
  
  doc.setFontSize(14);
  doc.text('Reproduction Summary', 20, y);
  y += 10;
  
  doc.autoTable({
    startY: y,
    head: [['Metric', 'Result', 'Target', 'Status']],
    body: [
      ['6-Week In-Calf Rate', '72%', '75%', 'Below Target'],
      ['Empty Rate', '9%', '10%', 'On Track'],
      ['Submission Rate (21 days)', '88%', '85%', 'Exceeding'],
      ['Conception Rate', '55%', '52%', 'Exceeding'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 57, 50] },
  });
  
  return doc.lastAutoTable.finalY + 10;
}

function generateFinancialReport(doc: jsPDF, startY: number, sections?: string[]): number {
  let y = startY;
  
  doc.setFontSize(14);
  doc.setTextColor(30, 57, 50);
  doc.text('Financial Summary', 20, y);
  y += 15;
  
  doc.autoTable({
    startY: y,
    head: [['Category', 'Budget', 'Actual', 'Variance']],
    body: [
      ['Milk Revenue', '$1,020,000', '$1,007,250', '-$12,750'],
      ['Livestock Sales', '$80,000', '$92,500', '+$12,500'],
      ['Total Revenue', '$1,100,000', '$1,099,750', '-$250'],
      ['Feed & Grazing', '$165,000', '$172,400', '+$7,400'],
      ['Labour', '$132,000', '$128,500', '-$3,500'],
      ['Animal Health', '$44,000', '$41,200', '-$2,800'],
      ['Total Expenses', '$738,000', '$745,600', '+$7,600'],
      ['Operating Profit', '$362,000', '$354,150', '-$7,850'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 57, 50] },
  });
  
  y = doc.lastAutoTable.finalY + 15;
  
  doc.setFontSize(14);
  doc.text('Key Financial Metrics', 20, y);
  y += 10;
  
  doc.autoTable({
    startY: y,
    head: [['Metric', 'Value', 'Industry Avg', 'Percentile']],
    body: [
      ['Cost per kg MS', '$3.95', '$4.20', '72nd'],
      ['Operating Profit/kg MS', '$4.25', '$3.80', '68th'],
      ['Return on Assets', '8.2%', '6.5%', '75th'],
      ['Debt per kg MS', '$15', '$18', '65th'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 57, 50] },
  });
  
  return doc.lastAutoTable.finalY + 10;
}

function generateTreatmentReport(doc: jsPDF, startY: number, sections?: string[]): number {
  let y = startY;
  
  doc.setFontSize(14);
  doc.setTextColor(30, 57, 50);
  doc.text('Treatment Summary', 20, y);
  y += 15;
  
  doc.autoTable({
    startY: y,
    head: [['Treatment Type', 'Count', 'Animals Treated', 'Success Rate']],
    body: [
      ['Mastitis', '45', '38', '89%'],
      ['Lameness', '28', '25', '92%'],
      ['Metabolic', '12', '12', '100%'],
      ['Respiratory', '8', '7', '88%'],
      ['Other', '15', '14', '93%'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 57, 50] },
  });
  
  return doc.lastAutoTable.finalY + 10;
}

function generateCustomReport(doc: jsPDF, startY: number, sections?: string[]): number {
  let y = startY;
  
  doc.setFontSize(12);
  doc.setTextColor(60);
  doc.text('Custom report content will be generated based on selected sections.', 20, y);
  
  return y + 20;
}

function calculateNextRun(frequency: string): string {
  const now = new Date();
  
  switch (frequency) {
    case 'daily':
      now.setDate(now.getDate() + 1);
      break;
    case 'weekly':
      now.setDate(now.getDate() + 7);
      break;
    case 'monthly':
      now.setMonth(now.getMonth() + 1);
      break;
    case 'quarterly':
      now.setMonth(now.getMonth() + 3);
      break;
    case 'annually':
      now.setFullYear(now.getFullYear() + 1);
      break;
  }
  
  return now.toISOString();
}

function getNextMonthDate(): string {
  const now = new Date();
  now.setMonth(now.getMonth() + 1);
  now.setDate(1);
  return now.toISOString();
}

// ===== DATA REPORT ENDPOINTS =====
// These endpoints return JSON data for compliance and management reports

// Manager roles allowed to access reports
const REPORT_ALLOWED_ROLES = ['owner', 'manager', 'admin'];

/**
 * Check if user has permission to access reports
 */
function canAccessReports(userRole: string | undefined): boolean {
  if (!userRole) return false;
  return REPORT_ALLOWED_ROLES.includes(userRole.toLowerCase());
}

/**
 * GET /api/reports/animal-inventory
 * Returns overview of the herd with counts by breed/category
 * 
 * Response: {
 *   total: number,
 *   byBreed: { [breed: string]: number },
 *   byStatus: { [status: string]: number },
 *   animals: Array<{ id, visualTag, name, breed, dateOfBirth, status, sex }>
 * }
 */
router.get('/api/reports/animal-inventory', requireAuth, async (req: Request, res: Response) => {
  try {
    const farmId = (req.user as any).farmId;
    const userRole = (req.user as any).role;

    if (!canAccessReports(userRole)) {
      return res.status(403).json({ error: 'You do not have permission to access reports' });
    }

    // Get all animals for the farm
    const allAnimals = await db
      .select({
        id: animals.id,
        visualTag: animals.visualTag,
        name: animals.name,
        breed: animals.breed,
        dateOfBirth: animals.dateOfBirth,
        status: animals.status,
        sex: animals.sex,
        species: animals.species,
      })
      .from(animals)
      .where(eq(animals.farmId, farmId))
      .orderBy(animals.visualTag);

    // Group by breed
    const byBreed: Record<string, number> = {};
    for (const animal of allAnimals) {
      const breed = animal.breed || 'Unknown';
      byBreed[breed] = (byBreed[breed] || 0) + 1;
    }

    // Group by status
    const byStatus: Record<string, number> = {};
    for (const animal of allAnimals) {
      const status = animal.status || 'unknown';
      byStatus[status] = (byStatus[status] || 0) + 1;
    }

    // Calculate ages
    const animalsWithAge = allAnimals.map(animal => {
      let ageMonths: number | null = null;
      if (animal.dateOfBirth) {
        const dob = new Date(animal.dateOfBirth);
        const now = new Date();
        ageMonths = Math.floor((now.getTime() - dob.getTime()) / (1000 * 60 * 60 * 24 * 30));
      }
      return {
        ...animal,
        ageMonths,
      };
    });

    res.json({
      total: allAnimals.length,
      byBreed,
      byStatus,
      animals: animalsWithAge,
      generatedAt: new Date().toISOString(),
    });
  } catch (error) {
    logger.error({ error }, 'Failed to generate animal inventory report');
    res.status(500).json({ error: 'Failed to generate animal inventory report' });
  }
});

/**
 * GET /api/reports/health-records
 * Returns health records within a date range
 * Query params: from (YYYY-MM-DD), to (YYYY-MM-DD)
 * 
 * Response: {
 *   total: number,
 *   byType: { [type: string]: number },
 *   records: Array<{ id, animalId, animalTag, recordDate, recordType, description, ... }>
 * }
 */
router.get('/api/reports/health-records', requireAuth, async (req: Request, res: Response) => {
  try {
    const farmId = (req.user as any).farmId;
    const userRole = (req.user as any).role;

    if (!canAccessReports(userRole)) {
      return res.status(403).json({ error: 'You do not have permission to access reports' });
    }

    // Parse date range (default to last 30 days)
    const now = new Date();
    const defaultFrom = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
    
    const fromDate = req.query.from ? String(req.query.from) : defaultFrom.toISOString().split('T')[0];
    const toDate = req.query.to ? String(req.query.to) : now.toISOString().split('T')[0];

    // Get health records with animal info
    const records = await db
      .select({
        id: animalHealthRecords.id,
        animalId: animalHealthRecords.animalId,
        animalTag: animals.visualTag,
        animalName: animals.name,
        recordDate: animalHealthRecords.recordDate,
        recordType: animalHealthRecords.recordType,
        description: animalHealthRecords.description,
        treatment: animalHealthRecords.treatment,
        veterinarian: animalHealthRecords.veterinarian,
        cost: animalHealthRecords.cost,
        notes: animalHealthRecords.notes,
        createdAt: animalHealthRecords.createdAt,
      })
      .from(animalHealthRecords)
      .innerJoin(animals, eq(animalHealthRecords.animalId, animals.id))
      .where(
        and(
          eq(animals.farmId, farmId),
          gte(animalHealthRecords.recordDate, fromDate),
          lte(animalHealthRecords.recordDate, toDate)
        )
      )
      .orderBy(desc(animalHealthRecords.recordDate));

    // Group by type
    const byType: Record<string, number> = {};
    let totalCost = 0;
    for (const record of records) {
      const type = record.recordType || 'other';
      byType[type] = (byType[type] || 0) + 1;
      if (record.cost) {
        totalCost += parseFloat(record.cost);
      }
    }

    res.json({
      total: records.length,
      byType,
      totalCost: totalCost.toFixed(2),
      dateRange: { from: fromDate, to: toDate },
      records,
      generatedAt: new Date().toISOString(),
    });
  } catch (error) {
    logger.error({ error }, 'Failed to generate health records report');
    res.status(500).json({ error: 'Failed to generate health records report' });
  }
});

/**
 * GET /api/reports/timesheet-summary
 * Returns hours worked per staff member within a date range
 * Query params: from (YYYY-MM-DD), to (YYYY-MM-DD)
 * 
 * Response: {
 *   totalHours: number,
 *   totalEntries: number,
 *   byStaff: Array<{ staffId, staffName, totalHours, entries }>
 * }
 */
router.get('/api/reports/timesheet-summary', requireAuth, async (req: Request, res: Response) => {
  try {
    const farmId = (req.user as any).farmId;
    const userRole = (req.user as any).role;

    if (!canAccessReports(userRole)) {
      return res.status(403).json({ error: 'You do not have permission to access reports' });
    }

    // Parse date range (default to last 30 days)
    const now = new Date();
    const defaultFrom = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
    
    const fromDate = req.query.from ? String(req.query.from) : defaultFrom.toISOString().split('T')[0];
    const toDate = req.query.to ? String(req.query.to) : now.toISOString().split('T')[0];

    // Get timesheet entries with staff info
    const entries = await db
      .select({
        id: timesheets.id,
        staffProfileId: timesheets.staffProfileId,
        staffName: users.name,
        clockIn: timesheets.clockIn,
        clockOut: timesheets.clockOut,
        hoursWorked: timesheets.hoursWorked,
        status: timesheets.status,
        notes: timesheets.notes,
      })
      .from(timesheets)
      .innerJoin(staffProfiles, eq(timesheets.staffProfileId, staffProfiles.id))
      .innerJoin(users, eq(staffProfiles.userId, users.id))
      .where(
        and(
          eq(timesheets.farmId, farmId),
          gte(timesheets.clockIn, new Date(fromDate)),
          lte(timesheets.clockIn, new Date(toDate + 'T23:59:59'))
        )
      )
      .orderBy(desc(timesheets.clockIn));

    // Aggregate by staff
    const staffMap = new Map<string, {
      staffId: string;
      staffName: string;
      totalHours: number;
      entries: number;
    }>();

    let totalHours = 0;
    for (const entry of entries) {
      const hours = entry.hoursWorked ? parseFloat(entry.hoursWorked) : 0;
      totalHours += hours;

      const existing = staffMap.get(entry.staffProfileId);
      if (existing) {
        existing.totalHours += hours;
        existing.entries += 1;
      } else {
        staffMap.set(entry.staffProfileId, {
          staffId: entry.staffProfileId,
          staffName: entry.staffName || 'Unknown',
          totalHours: hours,
          entries: 1,
        });
      }
    }

    // Convert to array and sort by hours
    const byStaff = Array.from(staffMap.values())
      .map(s => ({ ...s, totalHours: parseFloat(s.totalHours.toFixed(2)) }))
      .sort((a, b) => b.totalHours - a.totalHours);

    res.json({
      totalHours: parseFloat(totalHours.toFixed(2)),
      totalEntries: entries.length,
      dateRange: { from: fromDate, to: toDate },
      byStaff,
      generatedAt: new Date().toISOString(),
    });
  } catch (error) {
    logger.error({ error }, 'Failed to generate timesheet summary report');
    res.status(500).json({ error: 'Failed to generate timesheet summary report' });
  }
});

/**
 * GET /api/reports/safety
 * Returns safety compliance summary including hazards, incidents, and training
 * 
 * Response: {
 *   hazards: { open, resolved, byRiskLevel },
 *   tasks: { pending, completed, overdue },
 *   equipment: { total, needingService, operational },
 *   recentHazards: Array<hazard>
 * }
 */
router.get('/api/reports/safety', requireAuth, async (req: Request, res: Response) => {
  try {
    const farmId = (req.user as any).farmId;
    const userRole = (req.user as any).role;

    if (!canAccessReports(userRole)) {
      return res.status(403).json({ error: 'You do not have permission to access reports' });
    }

    // Get hazard counts
    const allHazards = await db
      .select({
        id: farmHazards.id,
        title: farmHazards.title,
        status: farmHazards.status,
        riskLevel: farmHazards.riskLevel,
        identifiedAt: farmHazards.identifiedAt,
        location: farmHazards.location,
      })
      .from(farmHazards)
      .where(eq(farmHazards.farmId, farmId))
      .orderBy(desc(farmHazards.identifiedAt));

    const openHazards = allHazards.filter(h => 
      h.status === 'identified' || h.status === 'under_review'
    );
    const resolvedHazards = allHazards.filter(h => 
      h.status === 'resolved' || h.status === 'mitigated'
    );

    // Group hazards by risk level
    const byRiskLevel: Record<string, number> = {};
    for (const hazard of openHazards) {
      const level = hazard.riskLevel || 'unknown';
      byRiskLevel[level] = (byRiskLevel[level] || 0) + 1;
    }

    // Get task counts (safety-related)
    const allTasks = await db
      .select({
        id: tasks.id,
        status: tasks.status,
        dueDate: tasks.dueDate,
        category: tasks.category,
      })
      .from(tasks)
      .where(eq(tasks.farmId, farmId));

    const safetyTasks = allTasks.filter(t => t.category === 'safety' || t.category === 'maintenance');
    const pendingTasks = safetyTasks.filter(t => t.status === 'pending' || t.status === 'in_progress');
    const completedTasks = safetyTasks.filter(t => t.status === 'completed');
    const overdueTasks = pendingTasks.filter(t => 
      t.dueDate && new Date(t.dueDate) < new Date()
    );

    // Get equipment status
    const allEquipment = await db
      .select({
        id: equipment.id,
        name: equipment.name,
        status: equipment.status,
        nextServiceDue: equipment.nextServiceDue,
      })
      .from(equipment)
      .where(and(eq(equipment.farmId, farmId), eq(equipment.isActive, true)));

    const today = new Date().toISOString().split('T')[0];
    const equipmentNeedingService = allEquipment.filter(e => 
      e.status === 'maintenance_due' || 
      e.status === 'in_maintenance' ||
      (e.nextServiceDue && e.nextServiceDue < today)
    );
    const operationalEquipment = allEquipment.filter(e => e.status === 'operational');

    // Get recent hazards (last 10)
    const recentHazards = allHazards.slice(0, 10);

    res.json({
      hazards: {
        total: allHazards.length,
        open: openHazards.length,
        resolved: resolvedHazards.length,
        byRiskLevel,
      },
      tasks: {
        total: safetyTasks.length,
        pending: pendingTasks.length,
        completed: completedTasks.length,
        overdue: overdueTasks.length,
      },
      equipment: {
        total: allEquipment.length,
        needingService: equipmentNeedingService.length,
        operational: operationalEquipment.length,
        outOfService: allEquipment.filter(e => e.status === 'out_of_service').length,
      },
      recentHazards,
      generatedAt: new Date().toISOString(),
    });
  } catch (error) {
    logger.error({ error }, 'Failed to generate safety report');
    res.status(500).json({ error: 'Failed to generate safety report' });
  }
});

/**
 * GET /api/reports/equipment-maintenance
 * Returns equipment maintenance history and status
 * Query params: from (YYYY-MM-DD), to (YYYY-MM-DD)
 * 
 * Response: {
 *   equipment: Array<{ id, name, status, lastService, nextService }>,
 *   maintenanceRecords: Array<{ equipmentName, serviceDate, serviceType, cost }>,
 *   totalMaintenanceCost: number
 * }
 */
router.get('/api/reports/equipment-maintenance', requireAuth, async (req: Request, res: Response) => {
  try {
    const farmId = (req.user as any).farmId;
    const userRole = (req.user as any).role;

    if (!canAccessReports(userRole)) {
      return res.status(403).json({ error: 'You do not have permission to access reports' });
    }

    // Parse date range (default to last 90 days)
    const now = new Date();
    const defaultFrom = new Date(now.getTime() - 90 * 24 * 60 * 60 * 1000);
    
    const fromDate = req.query.from ? String(req.query.from) : defaultFrom.toISOString().split('T')[0];
    const toDate = req.query.to ? String(req.query.to) : now.toISOString().split('T')[0];

    // Get all equipment
    const allEquipment = await db
      .select({
        id: equipment.id,
        name: equipment.name,
        type: equipment.type,
        status: equipment.status,
        lastServiceDate: equipment.lastServiceDate,
        nextServiceDue: equipment.nextServiceDue,
        location: equipment.location,
      })
      .from(equipment)
      .where(and(eq(equipment.farmId, farmId), eq(equipment.isActive, true)))
      .orderBy(equipment.name);

    // Get maintenance records in date range
    const maintenanceRecords = await db
      .select({
        id: equipmentServiceHistory.id,
        equipmentId: equipmentServiceHistory.equipmentId,
        equipmentName: equipment.name,
        serviceDate: equipmentServiceHistory.serviceDate,
        serviceType: equipmentServiceHistory.serviceType,
        description: equipmentServiceHistory.description,
        cost: equipmentServiceHistory.cost,
        performedBy: equipmentServiceHistory.performedBy,
      })
      .from(equipmentServiceHistory)
      .innerJoin(equipment, eq(equipmentServiceHistory.equipmentId, equipment.id))
      .where(
        and(
          eq(equipment.farmId, farmId),
          gte(equipmentServiceHistory.serviceDate, fromDate),
          lte(equipmentServiceHistory.serviceDate, toDate)
        )
      )
      .orderBy(desc(equipmentServiceHistory.serviceDate));

    // Calculate total maintenance cost
    let totalCost = 0;
    for (const record of maintenanceRecords) {
      if (record.cost) {
        totalCost += parseFloat(record.cost);
      }
    }

    // Group by service type
    const byServiceType: Record<string, number> = {};
    for (const record of maintenanceRecords) {
      const type = record.serviceType || 'other';
      byServiceType[type] = (byServiceType[type] || 0) + 1;
    }

    res.json({
      equipment: allEquipment,
      maintenanceRecords,
      summary: {
        totalEquipment: allEquipment.length,
        totalMaintenanceRecords: maintenanceRecords.length,
        totalMaintenanceCost: totalCost.toFixed(2),
        byServiceType,
      },
      dateRange: { from: fromDate, to: toDate },
      generatedAt: new Date().toISOString(),
    });
  } catch (error) {
    logger.error({ error }, 'Failed to generate equipment maintenance report');
    res.status(500).json({ error: 'Failed to generate equipment maintenance report' });
  }
});

export default router;
