import { Router, Request, Response } from 'express';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

const router = Router();

// Extend jsPDF type for autoTable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
    lastAutoTable: { finalY: number };
  }
}

// Generate PDF report
router.post('/api/reports/generate-pdf', async (req: Request, res: Response) => {
  try {
    const { reportType, dateRange, sections, farmName = 'Demo Farm' } = req.body;
    
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Header
    doc.setFontSize(20);
    doc.setTextColor(30, 57, 50); // Dark green
    doc.text(getReportTitle(reportType), pageWidth / 2, 20, { align: 'center' });
    
    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text(farmName, pageWidth / 2, 28, { align: 'center' });
    doc.text(`Generated: ${new Date().toLocaleDateString('en-NZ')}`, pageWidth / 2, 35, { align: 'center' });
    
    if (dateRange) {
      doc.text(`Period: ${dateRange.start} to ${dateRange.end}`, pageWidth / 2, 42, { align: 'center' });
    }
    
    // Add horizontal line
    doc.setDrawColor(30, 57, 50);
    doc.setLineWidth(0.5);
    doc.line(20, 48, pageWidth - 20, 48);
    
    let yPosition = 58;
    
    // Generate content based on report type
    switch (reportType) {
      case 'nzfap':
        yPosition = generateNZFAPReport(doc, yPosition, sections);
        break;
      case 'fwfp':
        yPosition = generateFWFPReport(doc, yPosition, sections);
        break;
      case 'fep':
        yPosition = generateFEPReport(doc, yPosition, sections);
        break;
      case 'nait':
        yPosition = generateNAITReport(doc, yPosition, sections);
        break;
      case 'herd-performance':
        yPosition = generateHerdPerformanceReport(doc, yPosition, sections);
        break;
      case 'financial-summary':
        yPosition = generateFinancialReport(doc, yPosition, sections);
        break;
      case 'treatment-records':
        yPosition = generateTreatmentReport(doc, yPosition, sections);
        break;
      default:
        yPosition = generateCustomReport(doc, yPosition, sections);
    }
    
    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(150);
      doc.text(
        `Page ${i} of ${pageCount}`,
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: 'center' }
      );
      doc.text(
        'Generated by Pulse Farm Management',
        20,
        doc.internal.pageSize.getHeight() - 10
      );
    }
    
    // Return PDF as base64
    const pdfBase64 = doc.output('datauristring');
    
    res.json({
      success: true,
      pdf: pdfBase64,
      filename: `${reportType}-report-${new Date().toISOString().slice(0, 10)}.pdf`,
    });
  } catch (error) {
    console.error('PDF generation error:', error);
    res.status(500).json({ error: 'Failed to generate PDF report' });
  }
});

// Download PDF directly
router.get('/api/reports/download/:reportType', async (req: Request, res: Response) => {
  try {
    const { reportType } = req.params;
    const { startDate, endDate } = req.query;
    
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Generate report based on type
    doc.setFontSize(20);
    doc.text(getReportTitle(reportType), pageWidth / 2, 20, { align: 'center' });
    
    let yPosition = 40;
    
    switch (reportType) {
      case 'nzfap':
        yPosition = generateNZFAPReport(doc, yPosition);
        break;
      case 'financial':
        yPosition = generateFinancialReport(doc, yPosition);
        break;
      default:
        doc.text('Report content will be generated here', 20, yPosition);
    }
    
    // Set response headers for PDF download
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=${reportType}-report.pdf`);
    
    // Send PDF buffer
    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
    res.send(pdfBuffer);
  } catch (error) {
    console.error('PDF download error:', error);
    res.status(500).json({ error: 'Failed to download PDF report' });
  }
});

// Schedule report
router.post('/api/reports/schedule', async (req: Request, res: Response) => {
  try {
    const { reportId, frequency, recipients, format, nextRun } = req.body;
    
    // In production, save to database and set up cron job
    // For now, return success
    const scheduleId = `schedule-${Date.now()}`;
    
    res.json({
      success: true,
      scheduleId,
      message: `Report scheduled to run ${frequency}`,
      nextRun: nextRun || calculateNextRun(frequency),
    });
  } catch (error) {
    console.error('Schedule report error:', error);
    res.status(500).json({ error: 'Failed to schedule report' });
  }
});

// Get scheduled reports
router.get('/api/reports/scheduled', async (req: Request, res: Response) => {
  try {
    // In production, fetch from database
    const scheduledReports = [
      {
        id: 's1',
        reportId: 'nait',
        reportName: 'NAIT Compliance Report',
        frequency: 'monthly',
        nextRun: getNextMonthDate(),
        recipients: ['farm@example.com'],
        format: 'PDF',
        status: 'active',
        lastSent: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 's2',
        reportId: 'herd-performance',
        reportName: 'Herd Performance Report',
        frequency: 'monthly',
        nextRun: getNextMonthDate(),
        recipients: ['farm@example.com', 'manager@example.com'],
        format: 'PDF',
        status: 'active',
        lastSent: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ];
    
    res.json(scheduledReports);
  } catch (error) {
    console.error('Get scheduled reports error:', error);
    res.status(500).json({ error: 'Failed to fetch scheduled reports' });
  }
});

// Delete scheduled report
router.delete('/api/reports/scheduled/:id', async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    // In production, delete from database
    res.json({ success: true, message: 'Scheduled report deleted' });
  } catch (error) {
    console.error('Delete scheduled report error:', error);
    res.status(500).json({ error: 'Failed to delete scheduled report' });
  }
});

// Get report history
router.get('/api/reports/history', async (req: Request, res: Response) => {
  try {
    const { limit = 20 } = req.query;
    
    // In production, fetch from database
    const history = [
      {
        id: 'g1',
        name: 'NZFAP Compliance Report 2024',
        type: 'Compliance',
        generatedAt: new Date().toISOString(),
        generatedBy: 'System',
        format: 'PDF',
        size: '2.4 MB',
        status: 'ready',
      },
      {
        id: 'g2',
        name: 'Herd Performance - December 2024',
        type: 'Production',
        generatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
        generatedBy: 'System',
        format: 'PDF',
        size: '1.8 MB',
        status: 'ready',
      },
    ];
    
    res.json(history);
  } catch (error) {
    console.error('Get report history error:', error);
    res.status(500).json({ error: 'Failed to fetch report history' });
  }
});

// Helper functions
function getReportTitle(reportType: string): string {
  const titles: Record<string, string> = {
    'nzfap': 'NZFAP Compliance Report',
    'fwfp': 'Freshwater Farm Plan Report',
    'fep': 'Farm Environment Plan',
    'nait': 'NAIT Compliance Report',
    'herd-performance': 'Herd Performance Report',
    'financial-summary': 'Financial Summary Report',
    'treatment-records': 'Treatment Records Report',
  };
  return titles[reportType] || 'Farm Report';
}

function generateNZFAPReport(doc: jsPDF, startY: number, sections?: string[]): number {
  let y = startY;
  
  // Executive Summary
  doc.setFontSize(14);
  doc.setTextColor(30, 57, 50);
  doc.text('Executive Summary', 20, y);
  y += 10;
  
  doc.setFontSize(10);
  doc.setTextColor(60);
  doc.text('Overall Compliance Score: 92%', 20, y);
  y += 6;
  doc.text('Audit Status: Certified', 20, y);
  y += 6;
  doc.text('Next Audit Due: March 2025', 20, y);
  y += 15;
  
  // Compliance Summary Table
  doc.autoTable({
    startY: y,
    head: [['Category', 'Status', 'Score', 'Items Checked']],
    body: [
      ['Animal Welfare', 'Compliant', '95%', '12/12'],
      ['Biosecurity', 'Compliant', '90%', '8/8'],
      ['Food Safety', 'Compliant', '88%', '10/10'],
      ['Environment', 'Minor Issues', '85%', '9/10'],
      ['People', 'Compliant', '92%', '6/6'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 57, 50] },
  });
  
  y = doc.lastAutoTable.finalY + 15;
  
  // Non-Compliance Items
  doc.setFontSize(14);
  doc.setTextColor(30, 57, 50);
  doc.text('Items Requiring Attention', 20, y);
  y += 10;
  
  doc.autoTable({
    startY: y,
    head: [['Item', 'Category', 'Priority', 'Due Date']],
    body: [
      ['Update effluent management plan', 'Environment', 'Medium', '2024-03-15'],
      ['Staff training refresher', 'People', 'Low', '2024-04-01'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [184, 150, 62] },
  });
  
  return doc.lastAutoTable.finalY + 10;
}

function generateFWFPReport(doc: jsPDF, startY: number, sections?: string[]): number {
  let y = startY;
  
  doc.setFontSize(14);
  doc.setTextColor(30, 57, 50);
  doc.text('Freshwater Farm Plan Summary', 20, y);
  y += 10;
  
  doc.setFontSize(10);
  doc.setTextColor(60);
  doc.text('Plan Status: Active', 20, y);
  y += 6;
  doc.text('Certification: Certified until December 2025', 20, y);
  y += 6;
  doc.text('Actions Completed: 18/24 (75%)', 20, y);
  y += 15;
  
  // Risk Assessment Summary
  doc.autoTable({
    startY: y,
    head: [['Risk Area', 'Risk Level', 'Mitigation Status', 'Review Date']],
    body: [
      ['Nitrogen Leaching', 'Medium', 'In Progress', '2024-06-01'],
      ['Sediment Runoff', 'Low', 'Complete', '2024-03-01'],
      ['E. coli Contamination', 'Medium', 'In Progress', '2024-05-15'],
      ['Phosphorus Loss', 'Low', 'Complete', '2024-02-01'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 57, 50] },
  });
  
  return doc.lastAutoTable.finalY + 10;
}

function generateFEPReport(doc: jsPDF, startY: number, sections?: string[]): number {
  let y = startY;
  
  doc.setFontSize(14);
  doc.setTextColor(30, 57, 50);
  doc.text('Environmental Compliance Summary', 20, y);
  y += 15;
  
  doc.autoTable({
    startY: y,
    head: [['Metric', 'Current', 'Target', 'Status']],
    body: [
      ['Nitrogen Leaching (kg N/ha)', '28', '35', 'On Track'],
      ['GHG Emissions (t CO2e/ha)', '9.2', '10.5', 'On Track'],
      ['Water Quality Index', '85%', '80%', 'Exceeding'],
      ['Riparian Planting (m)', '2,450', '3,000', 'In Progress'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 57, 50] },
  });
  
  return doc.lastAutoTable.finalY + 10;
}

function generateNAITReport(doc: jsPDF, startY: number, sections?: string[]): number {
  let y = startY;
  
  doc.setFontSize(14);
  doc.setTextColor(30, 57, 50);
  doc.text('NAIT Compliance Summary', 20, y);
  y += 10;
  
  doc.setFontSize(10);
  doc.setTextColor(60);
  doc.text('NAIT Number: 12345678', 20, y);
  y += 6;
  doc.text('Total Animals Registered: 312', 20, y);
  y += 6;
  doc.text('Movements This Period: 45', 20, y);
  y += 15;
  
  doc.autoTable({
    startY: y,
    head: [['Movement Type', 'Count', 'Registered', 'Compliance']],
    body: [
      ['Arrivals', '23', '23', '100%'],
      ['Departures', '18', '18', '100%'],
      ['Deaths', '4', '4', '100%'],
      ['Tag Replacements', '2', '2', '100%'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 57, 50] },
  });
  
  return doc.lastAutoTable.finalY + 10;
}

function generateHerdPerformanceReport(doc: jsPDF, startY: number, sections?: string[]): number {
  let y = startY;
  
  doc.setFontSize(14);
  doc.setTextColor(30, 57, 50);
  doc.text('Production Summary', 20, y);
  y += 15;
  
  doc.autoTable({
    startY: y,
    head: [['Metric', 'This Season', 'Last Season', 'Change']],
    body: [
      ['Total Milk Solids (kg)', '118,500', '112,300', '+5.5%'],
      ['MS per Cow (kg)', '395', '374', '+5.6%'],
      ['MS per Hectare (kg)', '1,185', '1,123', '+5.5%'],
      ['Peak Milk (L/cow/day)', '2.2', '2.1', '+4.8%'],
      ['Milking Days', '275', '270', '+1.9%'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 57, 50] },
  });
  
  y = doc.lastAutoTable.finalY + 15;
  
  doc.setFontSize(14);
  doc.text('Reproduction Summary', 20, y);
  y += 10;
  
  doc.autoTable({
    startY: y,
    head: [['Metric', 'Result', 'Target', 'Status']],
    body: [
      ['6-Week In-Calf Rate', '72%', '75%', 'Below Target'],
      ['Empty Rate', '9%', '10%', 'On Track'],
      ['Submission Rate (21 days)', '88%', '85%', 'Exceeding'],
      ['Conception Rate', '55%', '52%', 'Exceeding'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 57, 50] },
  });
  
  return doc.lastAutoTable.finalY + 10;
}

function generateFinancialReport(doc: jsPDF, startY: number, sections?: string[]): number {
  let y = startY;
  
  doc.setFontSize(14);
  doc.setTextColor(30, 57, 50);
  doc.text('Financial Summary', 20, y);
  y += 15;
  
  doc.autoTable({
    startY: y,
    head: [['Category', 'Budget', 'Actual', 'Variance']],
    body: [
      ['Milk Revenue', '$1,020,000', '$1,007,250', '-$12,750'],
      ['Livestock Sales', '$80,000', '$92,500', '+$12,500'],
      ['Total Revenue', '$1,100,000', '$1,099,750', '-$250'],
      ['Feed & Grazing', '$165,000', '$172,400', '+$7,400'],
      ['Labour', '$132,000', '$128,500', '-$3,500'],
      ['Animal Health', '$44,000', '$41,200', '-$2,800'],
      ['Total Expenses', '$738,000', '$745,600', '+$7,600'],
      ['Operating Profit', '$362,000', '$354,150', '-$7,850'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 57, 50] },
  });
  
  y = doc.lastAutoTable.finalY + 15;
  
  doc.setFontSize(14);
  doc.text('Key Financial Metrics', 20, y);
  y += 10;
  
  doc.autoTable({
    startY: y,
    head: [['Metric', 'Value', 'Industry Avg', 'Percentile']],
    body: [
      ['Cost per kg MS', '$3.95', '$4.20', '72nd'],
      ['Operating Profit/kg MS', '$4.25', '$3.80', '68th'],
      ['Return on Assets', '8.2%', '6.5%', '75th'],
      ['Debt per kg MS', '$15', '$18', '65th'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 57, 50] },
  });
  
  return doc.lastAutoTable.finalY + 10;
}

function generateTreatmentReport(doc: jsPDF, startY: number, sections?: string[]): number {
  let y = startY;
  
  doc.setFontSize(14);
  doc.setTextColor(30, 57, 50);
  doc.text('Treatment Summary', 20, y);
  y += 15;
  
  doc.autoTable({
    startY: y,
    head: [['Treatment Type', 'Count', 'Animals Treated', 'Success Rate']],
    body: [
      ['Mastitis', '45', '38', '89%'],
      ['Lameness', '28', '25', '92%'],
      ['Metabolic', '12', '12', '100%'],
      ['Respiratory', '8', '7', '88%'],
      ['Other', '15', '14', '93%'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 57, 50] },
  });
  
  return doc.lastAutoTable.finalY + 10;
}

function generateCustomReport(doc: jsPDF, startY: number, sections?: string[]): number {
  let y = startY;
  
  doc.setFontSize(12);
  doc.setTextColor(60);
  doc.text('Custom report content will be generated based on selected sections.', 20, y);
  
  return y + 20;
}

function calculateNextRun(frequency: string): string {
  const now = new Date();
  
  switch (frequency) {
    case 'daily':
      now.setDate(now.getDate() + 1);
      break;
    case 'weekly':
      now.setDate(now.getDate() + 7);
      break;
    case 'monthly':
      now.setMonth(now.getMonth() + 1);
      break;
    case 'quarterly':
      now.setMonth(now.getMonth() + 3);
      break;
    case 'annually':
      now.setFullYear(now.getFullYear() + 1);
      break;
  }
  
  return now.toISOString();
}

function getNextMonthDate(): string {
  const now = new Date();
  now.setMonth(now.getMonth() + 1);
  now.setDate(1);
  return now.toISOString();
}

export default router;
